documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - '*.html'
          - '*.css'
          - '*.js'
          - 'docs/**/*'
          - 'LICENSE'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'
